apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: redis-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-app
    spec:
      containers:
      - name: redis-app
        image: redis
        ports:
        - containerPort: 6379
          name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: redis-app
spec:
  ports:
  - port: 6379
  selector:
    app: redis-app
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ms-name
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: ms-name
    spec:
      containers:
      - name: ms-name
        image: nexus:8082/demodocker/$PROJECT_NAME/
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: REDIS
          value: "redis-app"
---
apiVersion: v1
kind: Service
metadata:
  name: ms-name
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: ms-name
---
 apiVersion: networking.k8s.io/v1beta1
 kind: Ingress
 metadata:
   name: ms-name.project_name.local
 spec:
   rules:
   - host: ms-name.project_name.local
     http:
       paths:
       - path: /
         backend:
           serviceName: ms-name
           servicePort: 80